# docker-compose.yml

version: '3.8'

services:
  sas_running_back:
    container_name: sas_running_back
    build: .
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      - SAS_RUNNING_BACK_HOST=db
      - SAS_RUNNING_BACK_PORT=5432
      - SAS_RUNNING_BACK_DB_USER=user
      - SAS_RUNNING_BACK_DB_PASSWORD=password
      - SAS_RUNNING_BACK_DB_NAME=sas_running_db

  db:
    image: postgres:15-alpine
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=
      - POSTGRES_PASSWORD=
      - POSTGRES_DB=
