# docker-compose.yml

version: '3.8'

services:
  sas_running_back:
    container_name: sas_running_back
    build: .
    ports:
      - 8000:8000
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=
      - POSTGRES_PASSWORD=
      - POSTGRES_DB=
